[package]
name = "aoc_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "aoc_1"
path = "src/lib.rs"


[[bin]]
name ="aoc_1_main"
path = "src/main.rs"

[dependencies]
